# Generated by Django 5.0.2 on 2024-03-24 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_remove_customuser_username_customuser_date_joined'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
