# Generated by Django 5.0.2 on 2024-03-24 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_delete_customuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'permissions': [('change_owned_event', 'Can change owned event')]},
        ),
    ]
