# Generated by Django 5.0.2 on 2024-03-28 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_category_tag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
