# Generated by Django 5.0.2 on 2024-03-29 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_category_tag_event_categories_event_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='categories',
            new_name='category',
        ),
    ]
