# Generated by Django 5.0.2 on 2024-03-29 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_alter_event_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='categories',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='event',
            name='categories',
            field=models.CharField(choices=[('music', 'Music'), ('nightlife', 'Nightlife'), ('performing_visual_arts', 'Performing & Visual Arts'), ('holidays', 'Holidays'), ('health', 'Health'), ('hobbies', 'Hobbies'), ('business', 'Business'), ('food_drink', 'Food & Drink')], default='-', max_length=100),
        ),
    ]
