# Generated by Django 5.0.2 on 2024-03-29 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_remove_event_categories_delete_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
