# Generated by Django 5.0.2 on 2024-03-29 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_tag_event_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(choices=[('CE', 'Clare'), ('CN', 'Cavan'), ('CO', 'Cork'), ('CW', 'Carlow'), ('D', 'Dublin'), ('DL', 'Donegal'), ('G', 'Galway'), ('KE', 'Kildare'), ('KK', 'Kilkenny'), ('KY', 'Kerry'), ('LD', 'Longford'), ('LH', 'Louth'), ('LK', 'Limerick'), ('LM', 'Leitrim'), ('LS', 'Laois'), ('MH', 'Meath'), ('MN', 'Monaghan'), ('MO', 'Mayo'), ('OY', 'Offaly'), ('RN', 'Roscommon'), ('SO', 'Sligo'), ('TA', 'Tipperary'), ('WD', 'Waterford'), ('WH', 'Westmeath'), ('WW', 'Wicklow'), ('WX', 'Wexford')], max_length=2),
        ),
    ]
