# Generated by Django 5.0.2 on 2024-03-29 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_alter_event_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='categories',
            field=models.CharField(choices=[('music', 'Music'), ('nightlife', 'Nightlife'), ('performing_visual_arts', 'Performing & Visual Arts'), ('holidays', 'Holidays'), ('health', 'Health'), ('hobbies', 'Hobbies'), ('business', 'Business'), ('food_drink', 'Food & Drink')], max_length=100),
        ),
    ]
