# Generated by Django 5.0.2 on 2024-03-29 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_remove_event_latitude_remove_event_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='categories',
            field=models.CharField(choices=[('music', 'Music'), ('nightlife', 'Nightlife'), ('performing_visual_arts', 'Performing & Visual Arts'), ('holidays', 'Holidays'), ('health', 'Health'), ('hobbies', 'Hobbies'), ('business', 'Business'), ('food_drink', 'Food & Drink')], default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(max_length=200),
        ),
    ]
