# Generated by Django 5.0.2 on 2024-03-29 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0024_alter_event_categories_alter_event_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='county',
            field=models.CharField(blank=True, default='Dublin', max_length=100),
        ),
    ]
