# Generated by Django 5.0.2 on 2024-04-03 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0032_alter_event_county'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='county',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
