# Generated by Django 5.0.2 on 2024-04-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0034_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='event_image',
            field=models.ImageField(blank=True, null=True, upload_to='ticket_images/'),
        ),
    ]
