# Generated by Django 5.0.2 on 2024-04-06 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0035_ticket_event_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='event_image',
        ),
    ]
